In [199]:
from tensorflow.keras.applications import VGG19
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg19 import preprocess_input
from tensorflow.keras.models import Model

import glob
import numpy as np
import matplotlib.pyplot as plt

In [177]:
# %%bash
# gdown https://drive.google.com/uc?id=1DVXZZTunBgJLJBLQa34gordxZdkAuTVr
# unzip dogs_atoms_imagenet.zip > /dev/null

!pwd

/home/psuresh/Desktop/VGG-19-Image-Classification


In [200]:
# reading files from the given path
data_path = "/data/*.jpg"

In [207]:
# define the model
model = VGG19(weights='imagenet', include_top=True)

# load the labels from image_net
labels = np.load('labels/imagenet_labels.npy', allow_pickle=True)[()]

In [225]:
for img in glob.glob("data/*.jpg"):
    img_1 = image.load_img(img, target_size = (224,224))
    x = image.img_to_array(img_1)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)
    preds = model.predict(x)
    idx = (-preds).argsort()[:,:1]
    print(labels[idx[0][0]])
#     for i_, i in enumerate(idx[0]):
#         print(labels[i], '(' + str(preds[:, i][0]) + ')', '\n')

American lobster, Northern lobster, Maine lobster, Homarus americanus
convertible
racer, race car, racing car
wardrobe, closet, press
freight car
lynx, catamount
motor scooter, scooter
sorrel
pug, pug-dog
sandbar, sand bar
sandbar, sand bar
ice lolly, lolly, lollipop, popsicle
racer, race car, racing car
minivan
ski
racer, race car, racing car
dock, dockage, docking facility
passenger car, coach, carriage
Ibizan hound, Ibizan Podenco
yawl
bookshop, bookstore, bookstall
wine bottle
Ibizan hound, Ibizan Podenco
television, television system
pop bottle, soda bottle
magpie
groom, bridegroom
airliner
sliding door
shopping cart
moped
oxcart
streetcar, tram, tramcar, trolley, trolley car
missile
tabby, tabby cat
Labrador retriever
snowmobile
motor scooter, scooter
warplane, military plane
sorrel
jeep, landrover
groenendael
entertainment center
Siberian husky
Saluki, gazelle hound
tabby, tabby cat
Egyptian cat
minivan
folding chair
basset, basset hound
tub, vat
harvester, reaper
racer, race ca

In [206]:
preds

array([[1.24766011e-08, 2.01601358e-09, 1.46045531e-08, 2.65437539e-09,
        2.11669660e-09, 3.75609277e-09, 1.29875763e-08, 7.22712400e-07,
        2.52420959e-05, 1.86275804e-06, 1.49900303e-09, 6.86175099e-08,
        2.93307295e-07, 1.06097195e-06, 4.57633359e-06, 5.21888097e-08,
        6.22183693e-10, 1.04213109e-06, 1.79208819e-05, 1.62262282e-07,
        8.53087379e-09, 3.86841892e-09, 2.06628847e-08, 7.98150359e-06,
        7.44101953e-08, 4.80499551e-09, 4.28713864e-09, 2.68234190e-09,
        5.73535139e-08, 1.62801854e-07, 4.61983518e-09, 5.32382138e-09,
        1.47063295e-08, 8.97369068e-10, 1.24318644e-09, 1.66338026e-07,
        2.27552562e-07, 1.41121923e-08, 1.38164435e-09, 1.59319880e-09,
        2.86799584e-09, 1.52851495e-10, 4.84228213e-10, 8.85032314e-09,
        2.85906032e-09, 3.37574968e-09, 2.02000106e-09, 1.27929001e-09,
        1.06816591e-08, 9.31299482e-09, 5.83345061e-09, 1.00267425e-06,
        1.00461084e-09, 1.62566338e-09, 7.70055131e-09, 1.252786

[[559]]
0. folding chair (0.2573674) 



In [124]:
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

In [130]:
preds = model.predict(x)

In [131]:
preds.argsort()

array([[147, 349,  21, 139, 384, 350, 110,  25, 993, 148, 115,  97,  98,
        150,  28,  90, 116, 103, 974,  80, 100, 321,  23,  99, 392, 143,
         95, 945,  85, 294, 347,  93, 262, 336, 973,  81, 342, 346, 109,
         84, 360, 379, 140,   0, 125,  91, 335, 403, 393,  24, 396, 344,
        268, 343,  37, 145, 364, 296, 290,  89,  83,  22, 275, 763, 510,
        337, 255,  20, 309, 165,  38,  10, 391, 351, 329, 194, 198, 405,
        119, 345, 146,  17, 295, 957, 914, 201,  15, 795, 206, 252, 348,
        833, 690, 292, 322, 682,  36, 128,  42, 205, 331, 726, 390, 370,
         86, 175, 220,  82, 244, 114, 326, 306, 965,  57, 949, 906, 820,
        385, 142, 190,  43, 289,  39,   8, 926,   7,  16, 366,  11, 269,
        214, 895,  26,  18, 649, 136, 149, 144, 369,  44, 935, 801, 976,
        152, 158, 104, 365, 101,  34, 340,  41, 157, 376, 554, 210, 439,
        952,  13, 122, 557, 865, 715, 988, 227, 272, 994, 397, 685, 953,
        387,  63, 404, 375, 460,  49, 241, 483, 235

In [103]:
feature


array([[2.76100245e-08, 1.33990034e-06, 2.05064789e-05, 1.76070978e-06,
        4.87913940e-06, 2.49883169e-06, 6.12041561e-07, 3.91772716e-07,
        1.83540521e-07, 6.23128187e-07, 1.13075281e-07, 1.32377664e-07,
        2.81423013e-07, 1.82893672e-07, 2.42229589e-07, 1.05365189e-07,
        1.07694667e-07, 8.85024392e-08, 2.57641915e-07, 6.10432721e-07,
        4.95796009e-08, 1.02059428e-08, 1.39507947e-07, 8.71625758e-08,
        1.16820537e-07, 1.82230586e-08, 8.41053733e-08, 1.05798456e-07,
        3.11612212e-08, 4.82498876e-07, 1.10740039e-07, 4.78076572e-07,
        9.98151393e-08, 9.30585770e-07, 1.59196634e-06, 8.35053200e-08,
        6.74413769e-08, 3.40167254e-08, 4.22383621e-08, 3.91013884e-07,
        7.53513518e-07, 1.53175094e-07, 7.11159416e-08, 3.29900331e-07,
        1.28701288e-07, 5.90990737e-07, 2.89762329e-06, 2.20626316e-06,
        5.95606082e-07, 4.41098592e-07, 9.34649449e-07, 3.21059451e-05,
        6.93353456e-07, 6.24869983e-07, 3.87650880e-06, 8.500732

In [104]:
labels = np.load('dogs_atoms_imagenet/imagenet_labels.npy', allow_pickle=True)[()]

FileNotFoundError: [Errno 2] No such file or directory: 'dogs_atoms_imagenet/imagenet_labels.npy'